import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  dev: [{ type: "autogenerated", dirName: "dev" }],
  others: [{ type: "autogenerated", dirName: "others" }],
};

export default sidebars;
